package com.tutego.insel.solutions.ui.swing;

@SuppressWarnings("all")
public class ForteGui extends javax.swing.JFrame {

  private static final long serialVersionUID = 3583416176049964523L;

    /** Creates new form ForteGui */
    public ForteGui() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        HauptPanel = new javax.swing.JPanel();
        OptionenPanel = new javax.swing.JPanel();
        positionLabel = new javax.swing.JLabel();
        positionComboBox = new javax.swing.JComboBox();
        ausrichtungLabel = new javax.swing.JLabel();
        ausrichtungComboBox = new javax.swing.JComboBox();
        seitenZahlCheckBox = new javax.swing.JCheckBox();
        IconPanel = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        ButtonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        abbrechenButton = new javax.swing.JButton();
        formatButton = new javax.swing.JButton();
        
        setTitle("Seitenzahlen");
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        HauptPanel.setLayout(new java.awt.GridLayout(1, 0));
        
        OptionenPanel.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        OptionenPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(4, 4, 4, 4)));
        positionLabel.setText("Position:");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 0.5;
        OptionenPanel.add(positionLabel, gridBagConstraints1);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        OptionenPanel.add(positionComboBox, gridBagConstraints1);
        
        ausrichtungLabel.setText("Ausrichtung:");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.insets = new java.awt.Insets(7, 0, 0, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        OptionenPanel.add(ausrichtungLabel, gridBagConstraints1);
        
        ausrichtungComboBox.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ausrichtungComboBoxActionPerformed(evt);
            }
        });
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 7, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        OptionenPanel.add(ausrichtungComboBox, gridBagConstraints1);
        
        seitenZahlCheckBox.setSelected(true);
        seitenZahlCheckBox.setText("Seitenzahl auf erster Seite");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        OptionenPanel.add(seitenZahlCheckBox, gridBagConstraints1);
        
        HauptPanel.add(OptionenPanel);
        
        IconPanel.setLayout(new java.awt.BorderLayout());
        
        IconPanel.setBorder(new javax.swing.border.TitledBorder(" Vorschau "));
        iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLabel.setText("Icon");
        IconPanel.add(iconLabel, java.awt.BorderLayout.CENTER);
        
        HauptPanel.add(IconPanel);
        
        getContentPane().add(HauptPanel, java.awt.BorderLayout.CENTER);
        
        ButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        
        okButton.setText("OK");
        ButtonPanel.add(okButton);
        
        abbrechenButton.setText("Abbrechen");
        ButtonPanel.add(abbrechenButton);
        
        formatButton.setMnemonic(70);
        formatButton.setText("Format...");
        ButtonPanel.add(formatButton);
        
        getContentPane().add(ButtonPanel, java.awt.BorderLayout.SOUTH);
        
        pack();
    }//GEN-END:initComponents

    private void ausrichtungComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ausrichtungComboBoxActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_ausrichtungComboBoxActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String[] args) {
        new ForteGui().setVisible( true );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HauptPanel;
    private javax.swing.JPanel OptionenPanel;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JComboBox positionComboBox;
    private javax.swing.JLabel ausrichtungLabel;
    private javax.swing.JComboBox ausrichtungComboBox;
    private javax.swing.JCheckBox seitenZahlCheckBox;
    private javax.swing.JPanel IconPanel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton abbrechenButton;
    private javax.swing.JButton formatButton;
    // End of variables declaration//GEN-END:variables
}
